# Generated by Django 2.1.7 on 2019-04-08 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=255)),
                ('index', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('previous_hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
                ('hash', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockchainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=255)),
                ('index', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('previous_hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
                ('hash', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DuplicateBlockchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latest_valid_block_index', models.IntegerField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dup_blockchains', to='bcplatform.BlockchainUser')),
                ('members', models.ManyToManyField(blank=True, related_name='dup_other_blockchains', to='bcplatform.BlockchainUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='duplicateblock',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcplatform.DuplicateBlockchain'),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchains', to='bcplatform.BlockchainUser'),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='other_blockchains', to='bcplatform.BlockchainUser'),
        ),
        migrations.AddField(
            model_name='block',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcplatform.Blockchain'),
        ),
    ]
