# Generated by Django 2.1.7 on 2019-04-08 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicateblockchain',
            name='original_blockchain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bcplatform.Blockchain'),
            preserve_default=False,
        ),
    ]
