# Generated by Django 2.1.7 on 2019-04-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcplatform', '0002_duplicateblockchain_original_blockchain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duplicateblockchain',
            old_name='latest_valid_block_index',
            new_name='first_invalid_block_index',
        ),
        migrations.AddField(
            model_name='duplicateblockchain',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
