# Generated by Django 2.1.7 on 2019-04-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcplatform', '0003_auto_20190408_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicateblockchain',
            name='first_invalid_block_index',
            field=models.IntegerField(null=True),
        ),
    ]
