# Generated by Django 2.1.7 on 2019-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcplatform', '0005_auto_20190320_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
