# Generated by Django 2.1.7 on 2019-03-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcplatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=255)),
                ('index', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
                ('hash', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='blockchainuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bcplatform.BlockchainUser'),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='members',
            field=models.ManyToManyField(related_name='_blockchain_members_+', to='bcplatform.BlockchainUser'),
        ),
        migrations.AddField(
            model_name='block',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcplatform.Blockchain'),
        ),
    ]
