# Generated by Django 2.1.7 on 2019-03-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcplatform', '0004_auto_20190319_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchains', to='bcplatform.BlockchainUser'),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='other_blockchains', to='bcplatform.BlockchainUser'),
        ),
    ]
