# Generated by Django 2.1.7 on 2019-04-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcplatform', '0006_auto_20190401_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='nonce',
            new_name='proof',
        ),
    ]
