# Generated by Django 2.1.7 on 2019-04-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcplatform', '0008_auto_20190401_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=255)),
                ('index', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('previous_hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
                ('hash', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='duplicateblockchain',
            name='blockchain_ptr',
        ),
        migrations.AddField(
            model_name='duplicateblockchain',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_blockchains', to='bcplatform.BlockchainUser'),
        ),
        migrations.AddField(
            model_name='duplicateblockchain',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duplicateblockchain',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='dup_other_blockchains', to='bcplatform.BlockchainUser'),
        ),
        migrations.AddField(
            model_name='duplicateblockchain',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duplicateblock',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcplatform.DuplicateBlockchain'),
        ),
    ]
